# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  tests_python:
    name: Test on Python ${{ matrix.python_version }} and Django ${{ matrix.django_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django_version: [ '2.2' ]
        python_version: [ '3.6' ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Test Django
      run: |
        python -W error::DeprecationWarning -W error::PendingDeprecationWarning \
           `which django-admin` test archivable_model --settings=archivable_model.tests.settings